from NumPyCreator import NumPyCreator as npc

def print_expected_output(output):
    print("=> expected output:\n{}".format(output))

if __name__=="__main__":
    print("==== FROM_LIST 1 ====")
    print_expected_output("array([[1,2,3],\n[6,3,4]])")
    print("=> real output:\n{}".format(npc.from_list([[1,2,3],[6,3,4]])))
    lol = npc.from_list([[1,2,3],[6,3,4]])
    print("\n==== FROM_LIST 2 ====")
    print_expected_output("None")
    print("=> real output:\n{}".format(npc.from_list([[1,2,3],[6,4]])))
    print("\n==== FROM_LIST 3 ====")
    print_expected_output("array(['1', '2', '3'],\n['a', 'b', 'c'],\n['5.0', '6.1', '7.8']], dtype='<U21')")
    print("=> real output:\n{}".format(npc.from_list([[1,2,3],['a','b','c'],[6,4,7]])))
    print("\n==== FROM_LIST 4 ====")
    print_expected_output("None")
    print("=> real output:\n{}".format(npc.from_list(((1,2),(3,4)))))
    print("\n==== FROM_TUPLE 1 ====")
    print_expected_output("array([['a','b','c'])")
    print("=> real output:\n{}".format(npc.from_tuple(("a","b","c"))))
    print("\n==== FROM_TUPLE 2 ====")
    print_expected_output("None")
    print("=> real output:\n{}".format(npc.from_tuple([[1,2,3],[6,3,4]])))
    print("\n==== FROM_ITERABLE ====")
    print_expected_output("array([0, 1, 2, 3, 4])")
    print("=> real output:\n{}".format(npc.from_iterable(range(5))))
    print("\n==== FROM_SHAPE ====")
    shape=(3,5)
    print_expected_output("array([[0, 0, 0, 0, 0],\n[0, 0, 0, 0, 0],\n[0, 0, 0, 0, 0]])")
    print("=> real output:\n{}".format(npc.from_shape(shape)))
    print("\n==== RANDOM ====")
    print_expected_output("array([[rand, rand, rand, rand, rand ],\n[rand, rand, rand, rand, rand],\n[rand, rand, rand, rand, rand]])")
    print("=> real output:\n{}".format(npc.random(shape)))
    print("\n==== IDENTITY ====")
    print_expected_output("array([[1., 0., 0., 0.],\n[0., 1., 0., 0.],\n[0., 0., 1., 0.],\n[0., 0., 0., 1.]])")
    print("=> real output:\n{}".format(npc.identity(4)))